trigger:
    batch: true
    branches:
        include:
        - main
        - develop
        - master

pool:
  name: 'Azure Pipelines'


variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')] #not used
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')] #not used
  test: ""

stages:
- template: templates/stage_level_templates/test_build_stage_template.yml # stage template to test, build and push
  parameters:
    projectFolder: Satya/InstagramApp/Frontend/InstagramCloneFrontend #${{variables.projectFolder}}
    buildOutputFolder: Satya/InstagramApp/Frontend/InstagramCloneFrontend/dist #${{variables.buildOutputFolder}}
    sourceFolder: Satya/InstagramApp/Frontend/InstagramCloneFrontend #${{variables.sourceFolder}}
    vmImageName: $(VMIMAGE)
    


- template: templates/stage_level_templates/az_deployment_stage_template.yml # stage template for azure resource deployment to Develop
  parameters:
    displayname: "appDeployfordev"
    vmImageName : $(VMIMAGE) #${{variables.vmImage}}
    azureSubscription : InstaService
    resourceGroup : "instarg"
    bicepFilePath : "Satya/InstagramApp/Frontend/infrastructure/main.bicep"
    parameterFilePath : "Satya/InstagramApp/Frontend/infrastructure/main.parameters.dev.json"
    jobName : "resourcedeployment"
    jobDescription : "deployemnt of resources"
    scriptType : "bash"
    environment: 'instadev'
    deploy: true

- template: templates/stage_level_templates/app_deployment_stage_template.yml #stage template for application deployment
  parameters:
    displayname: "appDeployfordevs"
    Artifacts: "drop"
    serviceConnection: InstaService
    subscriptionId: '82573c7d-8b1a-4ab0-a481-b40962a1c949'
    environment: 'instadev'
    appType: 'webApp'
    appName: 'instaclonefrontend-dev'

